const falas = {
    BEM_VINDO: 'Olá, bem vindo as falas de league of legends. Você pode me pedir para imitar um campeão.',
    FALAS: [
        'Simetria é tão entediante. Essa é do Jhin.',
        'Vivo pelo aplauso, você vai morrer por ele. Essa é do Jhin.',
        'A essência de algo é encontrada em sua ausência. Essa é do Jhin',
        'Os óculos? São só para leitura. Essa é do Master Yi.',
        'O segredo para imortalidade? Não morra. Essa é do Master Yi.',
        'A mente concentrada pode perfurar rochas. Essa é do Master Yi',
        'Não há cura para os tolos. Essa é do Yasuo.',
        'A espada acima de tudo! Exceto de uma boa bebida. Essa é do Yasuo.',
        'Há três certezas na vida: honra, morte e ressacas. Essa é do Yasuo.',
        'As trevas vem de dentro. Essa é do Zed.',
        'Despreze limitações. Essa é do Zed',
        'Ignorância é fatal. Essa é do Zed',
        'Equilíbrio é a maestria dos tolos. Essa é do Zed',
        'As pessoas temem o que não conseguem entender. Essa é da Syndra.',
        'Paciência não é uma virtude, ela é A Virtude. Essa é da Camille.',
        'Fuuuoooonn. Essa é do Bardo',
        'Faça um pedido, veja se as estrelas respondem eu espero. Essa é do Aurelion Sol',
        'Vamos ver quantas lanças você aguenta. Essa é da Kalista',
        'OK. Essa é do Rammus',
        'Domine a si mesmo, e dominará o inimigo. Essa é do Lee sin.',
        'Você é tão amável quanto um rato numa loja de noivas. Essa é do Tahm Kench.',
        'Eu vou engolir sua alma. Essa é do Veigar.',
        'Tamanho não é documento. Essa é do Teemo.',
        'Você provavelmente deveria se proteger. Essa é da Poppy.',
        'Farei vocês chorarem como filhotes. Essa é do Volibear.',
        'De gota em gota, jorrará o seu sangue. Essa é do Nocturne.',
        'Morra honradamente. Essa é do Xin Zhao.',
        'Eu sabia... mas, qual era a pergunta mesmo? Essa é do Heimerdinger.',
        'Não renasci das profudezas, simplesmente me recusei a morrer. Essa é do Urgot.',
        'Tome cuidado com homem que não tem nada a perder. Essa é do Varus.',
        'Quando dançar com a morte, conduza. Essa é do Varus',
        'Nem mesmo as chamas ou as profundezas poderão clamar por mim. Essa é do GP.',
        'Achei que nunca fosse me escolher. Essa é do Amumu.',
        'O lance não é quanto tempo você tem, é como você usa. Essa é do Ecko.',
        'Se é você que vai pagar eu tou dentro. Essa é do Gragas.',
        'Agonia, êxtase, paz cada passagem tem sua própria beleza. Essa é do Karthus.',
        'O equilibrio do poder deve ser preservado. Essa é do Kassadin.',
        'Todo mundo morre, alguns só precisam de uma ajudinha. Essa é do Lucian.',
        'Eles são privilegiados por morrerem aos meus pés. Essa é do Pantheon.',
        'Descansar é para os vivos. Essa é do Sion.',
        'Hora de trollar. Essa é do Trundle.',
        'Vamos a caça daqueles que cairam na escuridão. Essa é da Vayne.',
        'Eu fui criado pra isso, literalmente. Essa é do Zac.',
        'Bata primeiro, faça perguntas enquanto espanca. Essa é da Vi.',
        'Fique sabendo que se a situação fosse outra, eu não teria piedade de você. Essa é do Veigar.',
        'Nossa ira está além do seu controle. Essa é do Udyr.',
        'Não seremos enjaulados. Essa é do Sylas.',
        'Que tal um truque de mágica. Essa é do Shaco.',        
        'Enquanto eu viver, todos morrerão. Essa é do Renekton.',
        'Vivemos e morremos pela lâmina. Essa é do Talon.',
        'Tudo que está quebrado pode ser reforjado. Essa é da Riven.',
        'Vamos eliminar seus inimigos, isso vai ser divertido. Essa é da Orianna.',
        'Sentirão o terror da natureza. Essa é da Nidalee.',
        'As ilhas florescerão novamente. Essa é do Maokai.',
        'Prazer em conhecer vocês. Essa é da Lulu.',
        'A aurora chegou! Essa é da Leona.',
        'Nunca um sem o outro. Essa é dos Kindred.',
        'Você provará seu valor? Provavelmente não! Essa é do Kaynn',
        'Sempre confie em seu espirito. Essa é da Karma.',
        'Você é caça ou o caçador. Essa é da Kai sa.',
    ],
    ERRO: 'Algo deu errado!'
}

module.exports = falas;